<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="select.css">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="pequeno.css">
    <link rel="stylesheet" href="menos_pequeno.css">
    <link rel="stylesheet" href="medio.css">
    <link rel="stylesheet" href="largo.css">
    <link rel="stylesheet" href="botao_estado.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="select.js" defer></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>12 Arquétipos</title>
<style>
    .imagem2 {
        height:60vh;
        width:auto;
    }
    .imagem2 img{
        height:100%;
        width:auto;
    }
    .texto{
        display:flex;
        flex-direction: column;
        align-content: center;
        justify-content:center;


        font-size: 14px;
        color: black;
        margin: 5% 15% 5% 15%;
    }

    .texto .titulo{
        /* font-size: 30px; */
        text-align: center;
    }
    .texto .texto-conteudo{
        font-size: 25px;

    }
    .imagem3 {
        height:100vh;
        width:auto;
    }
    .imagem3 img{
        height:100%;
        width:100%;
    }
    .conteudo{
        display: flex;
        flex-direction: column;
        align-items:center;
        justify-content:space-around;

    }
    .youtube-icone{
        color: #A00F0F;
    }

    .videolink{
        display: flex;
        align-items:center;
        flex-direction: column;
        width: 100%;
        margin: 25px 0 25px 0;
    }

    .videolink-title{
        color: black;
    }
    .titulo
    {
        margin: 25px 0 25px 0;
        align-content: center;
        justify-content:center;
    }

    .videolink-icon{
        width: 85%;
        margin: auto;
    }
    /* .videolink-icon{
        height: 150px;
        width: auto;
    } */
</style>
</head>

<body>
    <div class="container_geral">

        <div class="imagem">
            <img src="./imgs/logo.jpg" alt="Logo">
        </div>

        <div style="margin-top:5%;" class="conteudo">
            <div class="imagem2">
                <img src="/%ARQUETIPO%.jpeg" alt="">
            </div>
            <div class="texto">
                <div class="titulo">
                    %TITULOARQUETIPO%
                </div>
                <div class="texto-conteudo">
                    %TEXTO%
                </div>
            </div>
            <div class="imagem3">   
            <img src="/o_%ARQUETIPO%_12_arquetipos.jpg">
            </div>
            <div class="videolink">
                <div class="videolink-title">
                        Saiba mais:    
                </div>

                <!-- retirar esse comentario quando ficar pronto o youtube -->
                <!-- <div class="videolink-icon">
                    <a href="%VIDEOLINK%"><i class="youtube-icone fa fa-youtube-play fa-3x"></i></a>

                </div> -->
            </div>
        </div>
        <!-- TODO retirar o comentario abaixo quando o problema com smtp com email for resolvido -->
        <!-- <div class="resultado-final">
        Email enviado com sucesso!
        </div> -->
        <button style="margin-bottom:80px;" onClick="JavaScript: window.history.back();" type="submit" class="button-submit">Voltar</button>
        
    </div>
</body>

</html>

<script type="text/javascript">


</script>