<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="select.css">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="pequeno.css">
    <link rel="stylesheet" href="menos_pequeno.css">
    <link rel="stylesheet" href="medio.css">
    <link rel="stylesheet" href="largo.css">
    <link rel="stylesheet" href="botao_estado.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="select.js" defer></script>

    <title>12 Arquétipos</title>
</head>

<body>
    <div class="container_geral">

        <div class="imagem">
            <img src="./imgs/logo.png" alt="Logo">
        </div>

        <div class="anunciado">
            <span>
                Este teste foi criado para que você se compreenda melhor através da
                identificação dos arquétipos que permeiam sua vida.
            </span>
            <img src="./imgs/divisor.png" alt="">
            <span>
                Os arquétipos são espécies de moldes ou padrões de comportamento, que
                definem formas específicas de ser. São também símbolos e imagens culturais
                que estão registrados no inconsciente coletivo.
            </span>
        </div>
        
        <div>
            deu certo!
        </div>

    </div>
</body>

</html>